version: '3.1'
services:
  user_service:
    container_name: user_api
    build: .
    ports:
      - "5051:80"
    environment: 
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_HTTPS_PORT: "5051"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - db
  db:
    container_name: user_db
    image: postgres:10-alpine
    restart: always
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
       - ./PostgresData:/var/lib/postgresql/data