version: '3.1'
services:
  user_service:
    build: .
    ports:
      - "5001:80"
    environment: 
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_HTTPS_PORT: "5001"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
       - ./PostgresData:/var/lib/postgresql/data