version: '3.1'
services:
  budget_service:
    container_name: "budget_api"
    build: .
    ports:
      - "5050:80"
    environment: 
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_HTTPS_PORT: "5050"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - "db"
  db:
    container_name: "budget_db"
    image: postgres:10-alpine
    restart: always
    ports:
     - "5433:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./PostgresData:/var/lib/postgresql/data